set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*256col*:Tc"

# Quick keys (no prefix needed)
bind -n C-t new-window \; run-shell "~/.tmux/plugins/tmux-resurrect/scripts/save.sh"
bind -n "C-Tab" next-window
bind -n "C-S-Tab" previous-window
bind -n M-Left previous-window
bind -n M-Right next-window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Show last folder name in tab instead of "zsh"
set -g automatic-rename-format '#{b:pane_current_path}'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

# Ctrl+b c → new tab
# Ctrl+b Ctrl+s → save now
# Ctrl+b Ctrl+r → restore
# Ctrl+b ? → list all keys

run '~/.tmux/plugins/tpm/tpm'
